name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # build-laravel:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./laravel

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Setup Make
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y make

  #     - name: Step 1 - Build (Laravel)
  #       run: make build

  #     - name: Step 2 - Tag (Laravel)
  #       run: make tag

  #     - name: Step 3 - Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.ACCOUNT_TOKEN }}

  #     - name: Step 4 - Push to GitHub Registry (Laravel)
  #       run: make push

  build-python:
    runs-on: ubuntu-latest
    # needs: build-laravel
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Step 1 - Build (Python)
        run: make build

      - name: Step 2 - Tag (Python)
        run: make tag

      - name: Step 3 - Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCOUNT_TOKEN }}

      - name: Step 4 - Push to GitHub Registry (Python)
        run: make push

  deploy:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
      - name: Barrier
        run: echo "Builds completed. Proceeding to webapp job."

  # webapp:
  #   runs-on: ubuntu-latest
  #   needs: deploy

  #   steps:
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Restart Azure Web App
  #       uses: azure/CLI@v2
  #       with:
  #         azcliversion: 2.30.0
  #         inlineScript: |
  #           az webapp restart --name movment --resource-group Movment-eg
